### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by zhangchuck** [zhangchuck/discord_quote_bot#86]
General improvements and standardization of logging

## Tasks

- [ ] Switch logging over to logzero
- [ ] Define a standard way of logging issues
- [ ] Document a process for when we expect log messages
- [ ] Rewrite all log messages into the new format

_Note:_ Originally in #76
